title: Captain Coder's Adventure Quest
description: A Unity Project
theme: just-the-docs

url: https://just-the-docs.github.io

# aux_links:
#   Project Template: https://github.com/jcollard/AdventureQuest-Unity-2021
